global using Autofac;
global using Autofac.Extensions.DependencyInjection;
global using Google.Apis.Auth.OAuth2;
global using Google.Apis.Services;
global using Google.Apis.Sheets.v4;
global using GRVAS.Data.MemberImporter.Models;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;